# Generated by Django 5.0.14 on 2026-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('food_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('is_best_seller', models.BooleanField(default=True)),
                ('delivery_time', models.CharField(default='20-30 Min', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
    ]
