# Generated by Django 6.0.7 on 2026-07-23 06:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension]),
        ),
    ]
