# Generated by Django 5.0.14 on 2026-07-23 06:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_category_image_alter_fooditem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('discount_text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension])),
                ('image_url', models.URLField(blank=True, help_text='External image URL (fallback if no uploaded image)', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description for the frontend.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback if no uploaded image)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback if no uploaded image)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback if no uploaded image)', max_length=500, null=True),
        ),
    ]
