# Generated by Django 5.0.14 on 2026-07-23 06:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension]),
        ),
    ]
